import { makeStyles, tokens } from "@fluentui/react-components";
import { CHART_COLORS } from "./DashboardPage-constants";

export const useStyles = makeStyles({
  root: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    minWidth: 0,
    height: "100%",
    overflow: "hidden",
  },
  filterRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "12px",
    marginBottom: "20px",
  },
  filterButtonUnselected: {
    backgroundColor: "rgba(96, 205, 255, 0.12)",
    color: "#ffffff",
    borderTopColor: "rgba(96, 205, 255, 0.3)",
    borderRightColor: "rgba(96, 205, 255, 0.3)",
    borderBottomColor: "rgba(96, 205, 255, 0.3)",
    borderLeftColor: "rgba(96, 205, 255, 0.3)",
    ":hover": {
      backgroundColor: "rgba(96, 205, 255, 0.28)",
      color: "#fff",
      borderTopColor: "rgba(96, 205, 255, 0.5)",
      borderRightColor: "rgba(96, 205, 255, 0.5)",
      borderBottomColor: "rgba(96, 205, 255, 0.5)",
      borderLeftColor: "rgba(96, 205, 255, 0.5)",
    },
  },
  tabPanel: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
  },
  tabPanelAllCalls: {
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  tabTableContent: {
    maxWidth: "90%",
    width: "100%",
    "& table": { tableLayout: "fixed" },
  },
  summaryDashboard: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gridTemplateRows: "1fr 1fr",
    gap: "clamp(8px, 1.5vh, 20px)",
    flex: "1 0 auto",
    minHeight: "360px",
    overflow: "hidden",
  },
  byUsageDashboard: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gridTemplateRows: "1fr 1fr",
    gap: "clamp(8px, 1.5vh, 20px)",
    height: "100%",
    minHeight: 0,
    overflow: "hidden",
    "& > *:nth-child(3)": {
      gridColumn: "1 / -1",
      justifySelf: "center",
      width: "calc((100% - 20px) / 2)",
      minWidth: 0,
    },
  },
  byUsageChartBlock: {
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    minWidth: 0,
  },
  byUsageChartContainer: {
    flex: 1,
    minHeight: 100,
    minWidth: 0,
    padding: "clamp(6px, 1vh, 12px)",
  },
  byUsageTitle: {
    flexShrink: 0,
    marginBottom: "2px",
    fontSize: "clamp(12px, 1.8vh, 14px)",
  },
  summaryKpiCell: {
    minHeight: 0,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
  },
  summaryKpiTitleSpacer: {
    flexShrink: 0,
    marginBottom: "4px",
    visibility: "hidden",
  },
  summaryKpiGrid: {
    flex: 1,
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gridTemplateRows: "minmax(0, 1fr) minmax(0, 1fr) minmax(0, 1fr) minmax(0, 1fr)",
    columnGap: "clamp(4px, 0.8vw, 12px)",
    rowGap: "clamp(4px, 0.6vh, 12px)",
  },
  summaryChartCellUsageSplit: {
    minHeight: 0,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
  },
  summaryKpiCard: {
    padding: "clamp(4px, 0.8vh, 12px) clamp(6px, 0.8vw, 14px)",
    borderRadius: "8px",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    backgroundColor: "#222235",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    "@media (max-height: 480px)": {
      flexDirection: "row",
      alignItems: "center",
      gap: "6px",
      padding: "4px 6px",
    },
  },
  summaryKpiLabel: {
    fontSize: "clamp(10px, 1.4vh, 12px)",
    color: tokens.colorNeutralForeground3,
    marginBottom: "clamp(2px, 0.4vh, 8px)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    flexShrink: 0,
    "@media (max-height: 480px)": {
      marginBottom: 0,
    },
  },
  summaryKpiValue: {
    fontSize: "clamp(12px, 1.8vh, 18px)",
    fontWeight: 600,
    color: CHART_COLORS.primary,
    overflow: "hidden",
    textOverflow: "ellipsis",
    wordBreak: "break-word",
    lineHeight: 1.2,
    minWidth: 0,
    "@media (max-height: 480px)": {
      flex: "1 1 auto",
      textAlign: "end",
    },
  },
  summaryChartTitle: {
    marginBottom: "4px",
    flexShrink: 0,
    textAlign: "start",
    fontSize: "clamp(12px, 1.6vh, 14px)",
  },
  summaryChartCell: {
    minHeight: 0,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
  },
  chartContainer: {
    width: "100%",
    height: "280px",
    marginBottom: "24px",
  },
  summaryChartContainer: {
    flex: 1,
    minHeight: 100,
    minWidth: 0,
    width: "100%",
    boxSizing: "border-box",
    backgroundColor: "#222235",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    borderRadius: "8px",
    padding: "12px",
    overflow: "hidden",
  },
  summaryChartContainerUsagePie: {
    padding: "clamp(4px, 0.5vh, 8px)",
  },
  summaryTabPanel: {
    height: "100%",
    minHeight: 0,
    overflowY: "auto",
    overflowX: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  tableWrap: {
    width: "100%",
    maxWidth: "100%",
    marginTop: "8px",
    marginBottom: "8px",
    borderRadius: "8px",
    overflow: "auto",
    boxShadow: `0 1px 3px ${tokens.colorNeutralShadowAmbient}, 0 1px 2px ${tokens.colorNeutralShadowKey}`,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  byModelTableWrapper: {
    "& table": { fontSize: "12px", tableLayout: "fixed" },
    "& th": { fontSize: "12px", whiteSpace: "normal", width: "100px" },
    "& th:first-of-type, & td:first-of-type": {
      width: "200px",
      minWidth: "200px",
      whiteSpace: "nowrap",
    },
  },
  byDayTableWrapper: {
    "& table": { fontSize: "13px", tableLayout: "fixed" },
    "& th": { fontSize: "13px", whiteSpace: "normal", width: "100px" },
    "& th:first-of-type, & td:first-of-type": {
      width: "100px",
      minWidth: "100px",
      whiteSpace: "nowrap",
    },
  },
  table: {
    width: "100%",
    minWidth: "max-content",
    tableLayout: "auto",
    borderCollapse: "collapse",
    fontSize: "13px",
  },
  thead: {
    backgroundColor: tokens.colorNeutralBackground3,
  },
  th: {
    padding: "10px 12px",
    textAlign: "start",
    fontWeight: 600,
    backgroundColor: tokens.colorNeutralBackground3,
    borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
    fontSize: "13px",
  },
  td: {
    padding: "12px 16px",
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    color: tokens.colorNeutralForeground1,
  },
  tdValue: {
    whiteSpace: "nowrap",
  },
  tbodyTr: {
    ":hover": {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  totalRow: {
    fontWeight: 600,
    backgroundColor: tokens.colorNeutralBackground3,
    borderTop: `1px solid ${tokens.colorNeutralStroke1}`,
    "& td": {
      borderBottom: "none",
      color: tokens.colorNeutralForeground1,
    },
  },
  emptyRow: {
    padding: "20px 16px",
    textAlign: "center",
    color: tokens.colorNeutralForeground3,
    fontStyle: "italic",
    backgroundColor: tokens.colorNeutralBackground1,
  },
  modelCell: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    whiteSpace: "nowrap",
  },
  modelTrashIcon: {
    color: "#6b7280",
    cursor: "pointer",
    flexShrink: 0,
    ":hover": {
      color: tokens.colorNeutralForeground1,
    },
  },
  paginationRow: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    flexWrap: "wrap",
    marginTop: "12px",
    marginBottom: "12px",
  },
  paginationSpacer: {
    minWidth: "72px",
  },
  downloadBlock: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
  },
  downloadButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    minWidth: "unset",
    paddingBlock: "2px",
    paddingInlineEnd: "6px",
    paddingInlineStart: "4px",
    borderRadius: "4px",
    fontSize: "12px",
    fontWeight: 600,
    backgroundColor: "#1e3a5f",
    color: "#e3f2fd",
    ":hover": {
      backgroundColor: "#2d4a6f",
      color: "#e3f2fd",
    },
  },
  typeBadge: {
    padding: "2px 8px",
    borderRadius: "4px",
    fontSize: "12px",
    fontWeight: 500,
  },
  typeTranslate: {
    backgroundColor: "rgba(132, 204, 22, 0.25)",
    color: CHART_COLORS.translation,
  },
  typeRewrite: {
    backgroundColor: "rgba(251, 146, 60, 0.25)",
    color: CHART_COLORS.rewrite,
  },
  typeTransform: {
    backgroundColor: "rgba(167, 139, 250, 0.25)",
    color: "#a78bfa",
  },
  allCallsTabPanel: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
  },
  allCallsTabContent: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    maxWidth: "100%",
    width: "100%",
  },
  allCallsTableWrapper: {
    display: "flex",
    flexDirection: "column",
    width: "80%",
    maxHeight: "100%",
    minHeight: 0,
    overflowX: "auto",
    overflowY: "hidden",
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    borderRadius: "8px",
    marginTop: "8px",
    boxShadow: `0 1px 3px ${tokens.colorNeutralShadowAmbient}, 0 1px 2px ${tokens.colorNeutralShadowKey}`,
    fontSize: "13px",
    "&::-webkit-scrollbar": {
      height: "10px",
    },
    "&::-webkit-scrollbar-track": {
      background: "transparent",
    },
    "&::-webkit-scrollbar-thumb": {
      background: "rgba(255, 255, 255, 0.28)",
      borderRadius: "5px",
    },
    "&::-webkit-scrollbar-thumb:hover": {
      background: "rgba(255, 255, 255, 0.45)",
    },
    scrollbarWidth: "thin",
    scrollbarColor: "rgba(255, 255, 255, 0.35) transparent",
  },
  allCallsHeaderRow: {
    display: "grid",
    gridTemplateColumns: "minmax(60px, 0.5fr) minmax(140px, 1.2fr) minmax(80px, 0.6fr) minmax(90px, 0.7fr) minmax(140px, 1.2fr) minmax(80px, 0.6fr) minmax(70px, 0.5fr)",
    backgroundColor: tokens.colorNeutralBackground3,
    borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
    minWidth: "fit-content",
    width: "100%",
  },
  allCallsBodyContainer: {
    flex: "1 1 auto",
    minHeight: 0,
    overflowY: "auto",
    overflowX: "hidden",
    display: "flex",
    flexDirection: "column",
    minWidth: "fit-content",
    width: "100%",
    "&::-webkit-scrollbar": {
      width: "10px",
    },
    "&::-webkit-scrollbar-track": {
      background: "transparent",
    },
    "&::-webkit-scrollbar-thumb": {
      background: "rgba(255, 255, 255, 0.28)",
      borderRadius: "5px",
    },
    "&::-webkit-scrollbar-thumb:hover": {
      background: "rgba(255, 255, 255, 0.45)",
    },
    scrollbarWidth: "thin",
    scrollbarColor: "rgba(255, 255, 255, 0.35) transparent",
  },
  allCallsBodyRow: {
    display: "grid",
    gridTemplateColumns: "minmax(60px, 0.5fr) minmax(140px, 1.2fr) minmax(80px, 0.6fr) minmax(90px, 0.7fr) minmax(140px, 1.2fr) minmax(80px, 0.6fr) minmax(70px, 0.5fr)",
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    cursor: "pointer",
    ":hover": {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
    width: "100%",
    color: tokens.colorNeutralForeground1,
  },
  allCallsExpandedRow: {
    width: "100%",
    padding: "16px 20px",
    backgroundColor: tokens.colorNeutralBackground2,
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    boxSizing: "border-box",
  },
  allCallsCell: {
    padding: "12px 16px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    display: "block",
    alignItems: "center",
  },
  allCallsHeaderCell: {
    padding: "10px 12px",
    textAlign: "start",
    fontWeight: 600,
    color: tokens.colorNeutralForeground1,
    overflow: "hidden",
    overflowWrap: "break-word",
    whiteSpace: "normal",
    display: "flex",
    alignItems: "center",
  },
  cellRight: {
    textAlign: "end",
  },
});
