import { makeStyles, tokens } from "@fluentui/react-components";
import { CHART_COLORS } from "./DashboardPage-constants";

export const useStyles = makeStyles({
  root: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    minWidth: 0,
    height: "100%",
    overflow: "hidden",
  },
  filterRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "12px",
    marginBottom: "20px",
  },
  filterButtonUnselected: {
    backgroundColor: "rgba(96, 205, 255, 0.12)",
    color: "#ffffff",
    borderColor: "rgba(96, 205, 255, 0.3)",
    ":hover": {
      backgroundColor: "rgba(96, 205, 255, 0.28)",
      color: "#fff",
      borderColor: "rgba(96, 205, 255, 0.5)",
    },
  },
  tabPanel: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
  },
  tabPanelAllCalls: {
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  tabTableContent: {
    maxWidth: "90%",
    width: "100%",
    "& $table": { tableLayout: "fixed" },
  },
  summaryDashboard: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gridTemplateRows: "1fr 1fr",
    gap: "clamp(8px, 1.5vh, 20px)",
    height: "100%",
    minHeight: 0,
    overflow: "hidden",
  },
  byUsageDashboard: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gridTemplateRows: "1fr 1fr",
    gap: "clamp(8px, 1.5vh, 20px)",
    height: "100%",
    minHeight: 0,
    overflow: "hidden",
    "& > *:nth-child(3)": {
      gridColumn: "1 / -1",
      justifySelf: "center",
      width: "calc((100% - 20px) / 2)",
      minWidth: 0,
    },
  },
  byUsageChartBlock: {
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    minWidth: 0,
  },
  byUsageChartContainer: {
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    padding: "clamp(6px, 1vh, 12px)",
  },
  byUsageTitle: {
    flexShrink: 0,
    marginBottom: "2px",
    fontSize: "clamp(12px, 1.8vh, 14px)",
  },
  summaryKpiCell: {
    minHeight: 0,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
  },
  summaryKpiTitleSpacer: {
    flexShrink: 0,
    marginBottom: "4px",
    visibility: "hidden",
  },
  summaryKpiGrid: {
    flex: 1,
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gridTemplateRows: "minmax(0, 1fr) minmax(0, 1fr) minmax(0, 1fr)",
    columnGap: "clamp(6px, 1vw, 12px)",
    rowGap: "clamp(6px, 1vw, 12px)",
  },
  summaryChartCellUsageSplit: {
    minHeight: 0,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
  },
  summaryChartCellRow2: {
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
  },
  summaryKpiCard: {
    padding: "clamp(6px, 1vh, 12px) clamp(8px, 1vw, 14px)",
    borderRadius: "8px",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    backgroundColor: "#222235",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
  },
  summaryKpiLabel: {
    fontSize: "clamp(10px, 1.4vh, 12px)",
    color: tokens.colorNeutralForeground3,
    marginBottom: "clamp(4px, 0.6vh, 8px)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  summaryKpiValue: {
    fontSize: "clamp(12px, 1.8vh, 18px)",
    fontWeight: 600,
    color: CHART_COLORS.primary,
    overflow: "hidden",
    textOverflow: "ellipsis",
    wordBreak: "break-word",
    lineHeight: 1.2,
  },
  summaryChartTitle: {
    marginBottom: "4px",
    flexShrink: 0,
    textAlign: "left",
    fontSize: "clamp(12px, 1.6vh, 14px)",
  },
  summaryChartCell: {
    minHeight: 0,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
  },
  kpiGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(160px, 1fr))",
    gap: "16px",
    marginBottom: "24px",
  },
  kpiCard: {
    padding: "16px",
    borderRadius: "8px",
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  kpiLabel: {
    fontSize: "12px",
    color: tokens.colorNeutralForeground3,
    marginBottom: "4px",
  },
  kpiValue: {
    fontSize: "18px",
    fontWeight: 600,
    color: CHART_COLORS.primary,
  },
  chartContainer: {
    width: "100%",
    height: "280px",
    marginBottom: "24px",
  },
  summaryChartContainer: {
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    width: "100%",
    boxSizing: "border-box",
    backgroundColor: "#222235",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    borderRadius: "8px",
    padding: "12px",
    overflow: "hidden",
  },
  summaryChartContainerUsagePie: {
    padding: "clamp(4px, 0.5vh, 8px)",
  },
  summaryTabPanel: {
    height: "100%",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  tableWrap: {
    width: "100%",
    maxWidth: "100%",
    marginTop: "8px",
    marginBottom: "8px",
    borderRadius: "8px",
    overflow: "auto",
    boxShadow: `0 1px 3px ${tokens.colorNeutralShadowAmbient}, 0 1px 2px ${tokens.colorNeutralShadowKey}`,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  table: {
    width: "100%",
    minWidth: "max-content",
    tableLayout: "auto",
    borderCollapse: "collapse",
    fontSize: "14px",
  },
  thead: {
    backgroundColor: tokens.colorNeutralBackground3,
  },
  th: {
    padding: "10px 12px",
    textAlign: "left",
    fontWeight: 600,
    backgroundColor: tokens.colorNeutralBackground3,
    borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
    fontSize: "14px",
  },
  td: {
    padding: "12px 16px",
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    color: tokens.colorNeutralForeground1,
  },
  tdValue: {
    whiteSpace: "nowrap",
  },
  tbodyTr: {
    ":hover": {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  totalRow: {
    fontWeight: 600,
    backgroundColor: tokens.colorNeutralBackground3,
    borderTop: `1px solid ${tokens.colorNeutralStroke1}`,
    "& td": {
      borderBottom: "none",
      color: tokens.colorNeutralForeground1,
    },
  },
  emptyRow: {
    padding: "20px 16px",
    textAlign: "center",
    color: tokens.colorNeutralForeground3,
    fontStyle: "italic",
    backgroundColor: tokens.colorNeutralBackground1,
  },
  modelCell: {
    minWidth: "200px",
    whiteSpace: "nowrap",
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  modelTrashIcon: {
    color: "#6b7280",
    cursor: "pointer",
    flexShrink: 0,
    ":hover": {
      color: tokens.colorNeutralForeground1,
    },
  },
  paginationRow: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    flexWrap: "wrap",
    marginTop: "12px",
    marginBottom: "12px",
  },
  typeBadge: {
    padding: "2px 8px",
    borderRadius: "4px",
    fontSize: "12px",
    fontWeight: 500,
  },
  typeTranslate: {
    backgroundColor: "rgba(132, 204, 22, 0.25)",
    color: CHART_COLORS.translation,
  },
  typeRewrite: {
    backgroundColor: "rgba(251, 146, 60, 0.25)",
    color: CHART_COLORS.rewrite,
  },
  typeTransform: {
    backgroundColor: "rgba(167, 139, 250, 0.25)",
    color: "#a78bfa",
  },
  allCallsTabPanel: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
  },
  allCallsTabContent: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    maxWidth: "100%",
    width: "100%",
  },
  allCallsTableOuter: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    marginTop: "8px",
    borderRadius: "8px",
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    boxShadow: `0 1px 3px ${tokens.colorNeutralShadowAmbient}, 0 1px 2px ${tokens.colorNeutralShadowKey}`,
  },
  allCallsHScroll: {
    flex: 1,
    minHeight: 0,
    overflowX: "scroll",
    overflowY: "hidden",
    display: "flex",
    flexDirection: "column",
    "&::-webkit-scrollbar": {
      height: "10px",
    },
    "&::-webkit-scrollbar-track": {
      background: "transparent",
    },
    "&::-webkit-scrollbar-thumb": {
      background: "rgba(255, 255, 255, 0.28)",
      borderRadius: "5px",
    },
    "&::-webkit-scrollbar-thumb:hover": {
      background: "rgba(255, 255, 255, 0.45)",
    },
    scrollbarWidth: "thin",
    scrollbarColor: "rgba(255, 255, 255, 0.35) transparent",
  },
  allCallsHeaderBlock: {
    flexShrink: 0,
  },
  allCallsHeaderTable: {
    width: "100%",
    minWidth: "1090px",
    tableLayout: "fixed",
    borderCollapse: "collapse",
    fontSize: "14px",
  },
  allCallsTheadNew: {
    backgroundColor: tokens.colorNeutralBackground3,
    borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  allCallsThNew: {
    padding: "10px 12px",
    textAlign: "left",
    fontWeight: 600,
    backgroundColor: tokens.colorNeutralBackground3,
    borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
    fontSize: "14px",
    color: tokens.colorNeutralForeground1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  allCallsBodyScroll: {
    flex: 1,
    minHeight: 0,
    overflowX: "visible",
    overflowY: "hidden",
  },
  allCallsBodyScrollInner: {
    marginRight: "-17px",
    paddingRight: "17px",
    overflowY: "auto",
    overflowX: "hidden",
    minWidth: "1090px",
    height: "100%",
    "&::-webkit-scrollbar": {
      width: "10px",
    },
    "&::-webkit-scrollbar-track": {
      background: "transparent",
    },
    "&::-webkit-scrollbar-thumb": {
      background: "rgba(255, 255, 255, 0.28)",
      borderRadius: "5px",
    },
    "&::-webkit-scrollbar-thumb:hover": {
      background: "rgba(255, 255, 255, 0.45)",
    },
    scrollbarWidth: "thin",
    scrollbarColor: "rgba(255, 255, 255, 0.35) transparent",
  },
  allCallsBodyTable: {
    width: "100%",
    minWidth: "1090px",
    tableLayout: "fixed",
    borderCollapse: "collapse",
    fontSize: "14px",
  },
  allCallsTdTruncate: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  refactoredTableWrapper: {
    display: "flex",
    flexDirection: "column",
    flex: "0 1 auto",
    alignSelf: "flex-start",
    maxHeight: "100%",
    minHeight: 0,
    overflowX: "auto",
    overflowY: "hidden",
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    borderRadius: "8px",
    marginTop: "8px",
    boxShadow: `0 1px 3px ${tokens.colorNeutralShadowAmbient}, 0 1px 2px ${tokens.colorNeutralShadowKey}`,
    "&::-webkit-scrollbar": {
      height: "10px",
    },
    "&::-webkit-scrollbar-track": {
      background: "transparent",
    },
    "&::-webkit-scrollbar-thumb": {
      background: "rgba(255, 255, 255, 0.28)",
      borderRadius: "5px",
    },
    "&::-webkit-scrollbar-thumb:hover": {
      background: "rgba(255, 255, 255, 0.45)",
    },
    scrollbarWidth: "thin",
    scrollbarColor: "rgba(255, 255, 255, 0.35) transparent",
  },
  refactoredHeaderRow: {
    display: "grid",
    gridTemplateColumns: "minmax(60px, 0.5fr) minmax(150px, 1.2fr) minmax(100px, 0.8fr) minmax(160px, 1.2fr) minmax(90px, 0.6fr) minmax(90px, 0.6fr) minmax(100px, 0.8fr) minmax(200px, 1.8fr) minmax(110px, 0.7fr) minmax(110px, 0.7fr) minmax(100px, 0.7fr) minmax(90px, 0.6fr) minmax(70px, 0.5fr)",
    backgroundColor: tokens.colorNeutralBackground3,
    borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
    minWidth: "fit-content",
    width: "100%",
  },
  refactoredBodyContainer: {
    flex: "1 1 auto",
    minHeight: 0,
    overflowY: "auto",
    overflowX: "hidden",
    display: "flex",
    flexDirection: "column",
    minWidth: "fit-content",
    width: "100%",
    "&::-webkit-scrollbar": {
      width: "10px",
    },
    "&::-webkit-scrollbar-track": {
      background: "transparent",
    },
    "&::-webkit-scrollbar-thumb": {
      background: "rgba(255, 255, 255, 0.28)",
      borderRadius: "5px",
    },
    "&::-webkit-scrollbar-thumb:hover": {
      background: "rgba(255, 255, 255, 0.45)",
    },
    scrollbarWidth: "thin",
    scrollbarColor: "rgba(255, 255, 255, 0.35) transparent",
  },
  refactoredBodyRow: {
    display: "grid",
    gridTemplateColumns: "minmax(60px, 0.5fr) minmax(150px, 1.2fr) minmax(100px, 0.8fr) minmax(160px, 1.2fr) minmax(90px, 0.6fr) minmax(90px, 0.6fr) minmax(100px, 0.8fr) minmax(200px, 1.8fr) minmax(110px, 0.7fr) minmax(110px, 0.7fr) minmax(100px, 0.7fr) minmax(90px, 0.6fr) minmax(70px, 0.5fr)",
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    ":hover": {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
    width: "100%",
    color: tokens.colorNeutralForeground1,
    fontSize: "14px",
  },
  refactoredCell: {
    padding: "12px 16px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    display: "block",
    alignItems: "center",
  },
  refactoredHeaderCell: {
    padding: "10px 12px",
    textAlign: "left",
    fontWeight: 600,
    color: tokens.colorNeutralForeground1,
    fontSize: "14px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    display: "block",
  },
  cellRight: {
    textAlign: "right",
  },
});
