import { makeStyles, tokens } from "@fluentui/react-components";

const useAppStyles = makeStyles({
  root: {
    height: "100vh",
    display: "flex",
    flexDirection: "column",
  },
  content: {
    flex: 1,
    display: "flex",
    padding: `0 ${tokens.spacingHorizontalXL} ${tokens.spacingVerticalXL} ${tokens.spacingHorizontalXL}`,
    gap: tokens.spacingHorizontalXL,
    overflow: "hidden",
  },
  panelStack: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    gap: "16px",
    padding: 0,
  },
  panelControls: {
    display: "flex",
    alignItems: "center",
    minHeight: "48px",
    marginBottom: tokens.spacingVerticalS,
  },
  transformPanelControlsRow: {
    justifyContent: "space-between",
    gap: tokens.spacingHorizontalM,
  },
  transformPanelControlsLeft: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: tokens.spacingHorizontalS,
  },
  panelFill: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
  },
  runButtonContainer: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    padding: `${tokens.spacingVerticalS} 0 0 0`,
    minHeight: "44px",
    flexShrink: 0,
  },
  runButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    minWidth: "180px",
    height: "44px",
    minHeight: "44px",
    padding: `0 ${tokens.spacingHorizontalM}`,
  },
  runButtonShortcut: {
    fontSize: "12px",
    opacity: 0.8,
    fontWeight: 400,
  },
  loadSampleButton: {
    backgroundColor: "#223328",
    color: "#e8f5e9",
    ":hover": {
      backgroundColor: "#2d4532",
      color: "#e8f5e9",
    },
  },
  loadingRoot: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100vh",
  },
  webOuter: {
    height: "100vh",
    boxSizing: "border-box",
    padding: "1% 1.5%",
    display: "flex",
    flexDirection: "column",
  },
  webOuterNoMargin: {
    height: "100vh",
    boxSizing: "border-box",
    padding: 0,
    display: "flex",
    flexDirection: "column",
  },
  webFrame: {
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    border: "1px solid #333",
    borderRadius: "4px",
  },
  webFrameSquare: {
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    border: "1px solid #333",
    borderRadius: 0,
  },
  loadingWebInner: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  loadingScreen: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "16px",
  },
  loadingScreenLogo: {
    width: "64px",
    height: "64px",
    objectFit: "contain",
  },
  loadingScreenText: {
    fontSize: "14px",
    opacity: 0.9,
  },
  rootInWeb: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
  },
});

export default useAppStyles;
