#!/bin/sh
# Wrapper to reset the admin user's password (web multi-user mode).
# Usage: reset-web-password <new-password>
# In Docker: docker exec <container> reset-web-password '<new-password>'
exec node "$(dirname "$0")/scripts/reset-web-password.js" "$@"
